Borrow/repay check removal
aave/aave-v3-core pull request #705
Opened 2022-08-08 17:32 UTC by The-3D

2022-08-09 10:06 UTC, miguelmtzinf requested changes

2022-08-09 10:06 UTC, miguelmtzinf commented on test-suites/validation-logic.spec.ts
> -  it('validateRepay() when variable borrowing and repaying in same block (revert expected)', async () => {
I believe its better to add these tests cases as non-reverting

2022-08-09 20:27 UTC, miguelmtzinf commented on test-suites/validation-logic.spec.ts
> -  it('validateRepay() when variable borrowing and repaying in same block (revert expected)', async () => {
Added tests

2022-08-09 20:27 UTC, miguelmtzinf approved these changes

2022-10-28 14:21 UTC, kyzia551 commented
looks fine

2022-10-28 15:15 UTC, merged